Repository MOV-AI/data-access-layer, pull requests merged in 2023-03, with the labels that each got.

#112 Fix updating a fleet member firmware overwrite redis-master DB
  dal/tools/backup.py
Labels: bug, help wanted

#111 Bugfix/bp 919/deprecation logs when using backup tool
  setup.py
Labels: bug

#119 fix robot recovery
  dal/scopes/fleetrobot.py
Labels: bug

#121 Hotfix/remove-API2-imports-from-backup-tool
  dal/tools/backup.py
Labels: bug, dependencies

#122 revert remove delete before set
  dal/movaidb/database.py
Labels: bug

#123 No-logs-shown-in-Fleetboard
  dal/db_handlers/time_series_db_handler.py
Labels: bug

#128 version 2.4.1.15
  dal/tools/backup.py
Labels: bug

#130 cicd : fix permissions
  .github/workflows/DeployOnGitRelease.yml
  .github/workflows/DeployOnMergeMain.yml
  .github/workflows/TestOnPR.yml
Labels: bug
