Repository MOV-AI/data-access-layer, pull requests merged in 2023-05, with the labels that each got.

#136 Hotfix BP-958 TaskGenerator
  dal/models/scopestree.py
Labels: bug

#137 Hotfix BP-958 TaskGenerator
  dal/models/scopestree.py
Labels: bug

#138 var eval fix
  dal/helpers/parsers.py
Labels: bug

#141 BP-1020 added imports inside functions instead
  dal/tools/backup.py
Labels: bug

#145 BP-990 - errors on zmq_client
  .github/CODEOWNERS
  dal/classes/protocols/wsredissub.py
Labels: bug

#146 BP-998 added new roles and permissions
  dal/models/acl.py
  dal/models/role.py
Labels: bug, enhancement

#144 BP-981 - backup tool returns 0 even when removing an non existing file
  dal/scopes/scope.py
  dal/tools/backup.py
Labels: bug

#148 Bugfix/bp 988 email notification roles
  dal/models/acl.py
  dal/models/role.py
  dal/tools/backup.py
Labels: SonarCloud

#147 version 2.4.1.21
  .github/CODEOWNERS
  dal/classes/protocols/wsredissub.py
  dal/models/acl.py
  dal/models/role.py
  dal/scopes/message.py
  dal/scopes/scope.py
  dal/tools/backup.py
Labels: bug
